# Generated by Django 4.2.11 on 2024-04-26 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor_app', '0002_alter_customuser_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='active_account',
            field=models.BooleanField(null=True),
        ),
    ]
