# Generated by Django 4.2.11 on 2024-05-04 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor_app', '0003_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='student',
            new_name='student_id',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='tutor',
            new_name='tutor_id',
        ),
    ]
